apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-v1-passwordless-identity
  namespace: your-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passwordless-identity
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: passwordless-identity
    spec:
      containers:
      - name: passwordless-identity
        image: index.docker.io/DOCKER_USER/PRIVATE_REPO_NAME:latest
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: environment-config
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      restartPolicy: Always
      volumes:
      - name: app-settings
        azureFile:
          secretName: storage-secret
          shareName: settings
          readOnly: true

---

apiVersion: v1
kind: Service
metadata:
  name: s-v1-passwordless-identity
  namespace: your-namespace
spec:
  ports:
    - port: 80
  selector:
    app: passwordless-identity
  type: NodePort